Merged PR 3953: Updated CI to test all supported version
Changes made:
BUILD: Updated CI to test all supported versions. Also, check to make sure the correct version of PHP is installed and used.
BUG: Constant modifier is not supported until 7.1.0 so remove from MissingPropertyReason.php
BUILD: Added a composer-dev.json to reference a local package in development CI. This is currently used by device-detection-php-onpremise and is reference a pipeline-php-core that resides in the same folder. Moving forwards for CI, we might want to add the pipeline-php-core as a submodule and reference that instead. This way it might impact device-detection-php-onpremise but will support development build and test without waiting for pipeline-php-core to be released.

diff --git a/build-and-test.yml b/build-and-test.yml
--- a/build-and-test.yml
+++ b/build-and-test.yml
@@ -9,14 +9,30 @@ strategy:
       phpVersion: 5.6
     PHP 7.2:
       phpVersion: 7.2
+    PHP 7.3:
+      phpVersion: 7.3
+    PHP 7.4:
+      phpVersion: 7.4
 
 steps:
+
 - script: |
+    sudo add-apt-repository ppa:ondrej/php
+    sudo apt-get update -y
+    sudo apt-get install -y php$(phpVersion)-dev
+    sudo apt-get install -y php$(phpVersion)-xml
+    sudo apt-get install -y php$(phpVersion)-mbstring
     sudo update-alternatives --set php /usr/bin/php$(phpVersion)
     sudo update-alternatives --set phar /usr/bin/phar$(phpVersion)
-    sudo update-alternatives --set phpdbg /usr/bin/phpdbg$(phpVersion)
-    sudo update-alternatives --set php-cgi /usr/bin/php-cgi$(phpVersion)
     sudo update-alternatives --set phar.phar /usr/bin/phar.phar$(phpVersion)
+
+    export versionc=`php -version | grep -Fc "$(phpVersion)"`
+    if [ $versionc -eq 0]; then
+      echo "Failed to install correct php version $(phpVersion)"
+      exit 1
+    else
+      echo "PHP $(phpVersion) installed."
+    fi
     php -version
   displayName: 'Use PHP version $(phpVersion)'
 
